site_name: CS-ZIJI-<课程名称> # TODO: 请修改项配置
repo_name: CS-ZIJI/F-MkDocs-Template # TODO: 请修改项配置
repo_url: https://github.com/CS-ZIJI/F-MkDocs-Template # TODO: 请修改项配置
edit_uri: blob/main/docs

copyright: 'Copyright &copy 2023 CS-ZIJI'

theme:
  name: material
  language: zh
  features:
    - navigation.tracking
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt
    edit: material/pencil
    view: material/eye

markdown_extensions:
  - toc:
      permalink: true # 每个标题都有锚点
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  - admonition
  - pymdownx.details # 可折叠的 admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
  - search:
      separator: '[\s\-\.]+'
  - git-committers:
      repository: CS-ZIJI/F-MkDocs-Template # TODO: 请修改本项配置
      branch: main
  - statistics:
      words_per_minute: 200

extra_css:
  - supports/css/base.css
  - supports/css/theme.css
  - supports/css/admonitions.css
  - https://jsd.cdn.zzko.cn/npm/katex@0.16.4/dist/katex.min.css

extra_javascript: 
  - supports/js/katex.js
  - https://jsd.cdn.zzko.cn/npm/katex@0.16.4/dist/katex.min.js

# ======================================== >>>
# TODO: 请修改本项配置

nav:
  - "封面": index.md
  - 0-x.md

# ======================================== <<<

